# Generated by Django 5.1.3 on 2024-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(default='token', max_length=255)),
                ('secret_key', models.CharField(default='secret_key', max_length=255)),
                ('admin', models.IntegerField(default=1)),
                ('webhook_url', models.URLField(default='https://7bb8-185-213-229-51.ngrok-free.app/webhook/', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
