# Generated by Django 5.1.3 on 2024-12-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.FloatField(),
        ),
    ]
